#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ ! -d ".chromie" ]; then
    mkdir -p .chromie
fi
SYSTEM_INFO_FILE=".chromie/system_info.env"
./scripts/collect_system_info.sh > "$SYSTEM_INFO_FILE"

profile="${CHROMIE_HARDWARE_PROFILE:-}"

# Allow .env.local to force the profile without sourcing arbitrary shell content.
if [ -z "$profile" ] && [ -f ".env.local" ]; then
  profile="$(awk -F= '/^[[:space:]]*CHROMIE_HARDWARE_PROFILE[[:space:]]*=/ {v=$2; gsub(/^[[:space:]]+|[[:space:]]+$/, "", v); gsub(/^"|"$/, "", v); gsub(/^'"'"'|"'"'"'$/, "", v); print v}' .env.local | tail -n1)"
fi

if [ -z "$profile" ]; then
  profile="$(./scripts/detect_hardware_profile.sh)"
fi

COMMON_ENV=".env.common"
PROFILE_ENV="env/profiles/${profile}.env"
LOCAL_ENV=".env.local"
RUNTIME_ENV=".env.runtime"
COMPOSE_ENV=".env"

echo "[env] Detected/selected hardware profile: $profile"

if [ ! -f "$COMMON_ENV" ]; then
  echo "[env][error] Missing $COMMON_ENV" >&2
  exit 1
fi

if [ ! -f "$PROFILE_ENV" ]; then
  echo "[env][warn] Missing $PROFILE_ENV; using env/profiles/default.env" >&2
  profile="default"
  PROFILE_ENV="env/profiles/default.env"
fi

{
  echo "# Generated by scripts/build_runtime_env.sh"
  echo "# Do not edit this file directly. Edit .env.common, env/profiles/*.env, or .env.local."
  echo
  echo "# ---- detected system info ----"
  cat "$SYSTEM_INFO_FILE"
  echo
  echo "# ---- common defaults ----"
  cat "$COMMON_ENV"
  echo
  echo "# ---- hardware profile: $profile ----"
  cat "$PROFILE_ENV"
  echo
  if [ -f "$LOCAL_ENV" ]; then
    echo "# ---- local overrides ----"
    cat "$LOCAL_ENV"
    echo
  fi
  echo "# ---- selected profile marker ----"
  echo "CHROMIE_ACTIVE_PROFILE=$profile"
  echo "CHROMIE_SYSTEM_INFO_FILE=$SYSTEM_INFO_FILE"
} > "$RUNTIME_ENV"

if [ -f "$COMPOSE_ENV" ] && ! grep -q "Generated by scripts/build_runtime_env.sh" "$COMPOSE_ENV"; then
  echo "[env][warn] Existing $COMPOSE_ENV is not generated by Chromie; leaving it unchanged." >&2
  echo "[env][warn] Plain 'docker compose ...' may not see .env.runtime. Prefer ./scripts/compose.sh ..." >&2
else
  cp "$RUNTIME_ENV" "$COMPOSE_ENV"
  echo "[env] Wrote $COMPOSE_ENV for Docker Compose compatibility"
fi

echo "[env] Wrote $RUNTIME_ENV"
echo "[env] System info: $SYSTEM_INFO_FILE"
